[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = false
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
optimizer = true
out = "out"
src = "src"
via_ir = true

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
