#!/usr/bin/env python3
"""Fetch real ETH/USD daily closes and generate test/RealPrices.sol (no fabrication).

Primary source: Coinbase Exchange public candles (no key). Fallback: CoinGecko.
Prices are written oldest -> newest, in USD scaled to WAD (1e18), as a pure Solidity
library the economic backtest imports. Re-run any time to refresh the series.
"""
import urllib.request
import json


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return json.load(urllib.request.urlopen(req, timeout=30))


def fetch_coinbase():
    # candle = [time, low, high, open, close, volume]; newest first
    d = _get("https://api.exchange.coinbase.com/products/ETH-USD/candles?granularity=86400")
    d.sort(key=lambda r: r[0])  # oldest -> newest
    return [float(r[4]) for r in d], "Coinbase Exchange ETH-USD daily candles (granularity=86400)"


def fetch_coingecko():
    d = _get("https://api.coingecko.com/api/v3/coins/ethereum/market_chart?vs_currency=usd&days=300")
    return [float(p[1]) for p in d["prices"]], "CoinGecko ETH/USD market_chart (days=300, daily)"


try:
    closes, source = fetch_coinbase()
except Exception as e:  # noqa: BLE001 - any network/parse failure -> fallback
    print("coinbase failed:", e, "-> trying coingecko")
    closes, source = fetch_coingecko()

n = len(closes)
lines = [f"        p[{i}] = uint256({int(round(c * 100))}) * 1e16;" for i, c in enumerate(closes)]

header = (
    "// SPDX-License-Identifier: MIT\n"
    "// Auto-generated by scripts/fetch_prices.py -- do not edit by hand.\n"
    "// Source: " + source + ".\n"
    "// " + str(n) + " daily closes, oldest to newest, USD scaled to WAD (1e18).\n"
    "pragma solidity ^0.8.24;\n\n"
    "library RealPrices {\n"
    "    function closesWad() internal pure returns (uint256[] memory p) {\n"
    "        p = new uint256[](" + str(n) + ");\n"
)
footer = "\n    }\n}\n"

with open("test/RealPrices.sol", "w") as f:
    f.write(header + "\n".join(lines) + footer)

print(f"wrote test/RealPrices.sol: {n} daily closes from {source}")
print(f"first={closes[0]:.2f} last={closes[-1]:.2f} min={min(closes):.2f} max={max(closes):.2f}")
