#!/usr/bin/env python3
"""Fetch real daily closes for a Coinbase product and generate a Solidity price library (no fabrication).

Usage:
    python3 scripts/fetch_prices.py [PRODUCT] [OUTPATH] [LIBNAME]
    python3 scripts/fetch_prices.py                                  # ETH-USD -> test/RealPrices.sol
    python3 scripts/fetch_prices.py BTC-USD test/RealPricesBTC.sol RealPricesBTC
"""
import urllib.request
import json
import sys

PRODUCT = sys.argv[1] if len(sys.argv) > 1 else "ETH-USD"
OUTPATH = sys.argv[2] if len(sys.argv) > 2 else "test/RealPrices.sol"
LIBNAME = sys.argv[3] if len(sys.argv) > 3 else "RealPrices"

_COINGECKO_ID = {"ETH-USD": "ethereum", "BTC-USD": "bitcoin"}


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return json.load(urllib.request.urlopen(req, timeout=30))


def fetch_coinbase():
    d = _get(f"https://api.exchange.coinbase.com/products/{PRODUCT}/candles?granularity=86400")
    d.sort(key=lambda r: r[0])
    return [float(r[4]) for r in d], f"Coinbase Exchange {PRODUCT} daily candles (granularity=86400)"


def fetch_coingecko():
    coin = _COINGECKO_ID.get(PRODUCT, "ethereum")
    d = _get(f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart?vs_currency=usd&days=300")
    return [float(p[1]) for p in d["prices"]], f"CoinGecko {coin} market_chart (days=300, daily)"


try:
    closes, source = fetch_coinbase()
except Exception as e:  # noqa: BLE001
    print("coinbase failed:", e, "-> trying coingecko")
    closes, source = fetch_coingecko()

n = len(closes)
lines = [f"        p[{i}] = uint256({int(round(c * 100))}) * 1e16;" for i, c in enumerate(closes)]

header = (
    "// SPDX-License-Identifier: MIT\n"
    "// Auto-generated by scripts/fetch_prices.py -- do not edit by hand.\n"
    "// Source: " + source + ".\n"
    "// " + str(n) + " daily closes, oldest to newest, USD scaled to WAD (1e18).\n"
    "pragma solidity ^0.8.24;\n\n"
    "library " + LIBNAME + " {\n"
    "    function closesWad() internal pure returns (uint256[] memory p) {\n"
    "        p = new uint256[](" + str(n) + ");\n"
)
footer = "\n    }\n}\n"

with open(OUTPATH, "w") as f:
    f.write(header + "\n".join(lines) + footer)

print(f"wrote {OUTPATH} ({LIBNAME}): {n} daily closes from {source}")
print(f"first={closes[0]:.2f} last={closes[-1]:.2f} min={min(closes):.2f} max={max(closes):.2f}")
